##
##   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
##  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
##  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
##  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
##  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
##  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝

import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

live_config_reload = true

[cursor]
style = "beam"

[font]
size = 17
normal.family = "LigaSFMonoNerdFont"

[font.bold]
family = "LigaSFMonoNerdFont"
style = "Bold"

[font.italic]
family = "LigaSFMonoNerdFont"
style = "italic"

[mouse]
hide_when_typing = false

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[scrolling]
history = 100000
multiplier = 6


[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15

startup_mode = "Maximized"

decorations = "None"

opacity = 0.7
blur = true

